[[work]]
title = "Alleyway in Spring"
medium = "watercolor on cotton paper"
yearCreated = "2024"
size = "9 x 12 inches"
price = "400"
imageURL = "test"

[[work]]
title = "Brunette"
medium = "oil pastel on paper"
yearCreated = "2024"
size = "5 x 6.5"
price = "80"
imageURL = "test"
